# Generated by Django 6.0.6 on 2026-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('main_course', 'Main Course'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('drink', 'Drink')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prep_time_minutes', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('is_halal', models.BooleanField(default=True)),
                ('is_spicy', models.BooleanField(default=False)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menus/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='menus/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
